apiVersion: v1
kind: ReplicationController
metadata:
  name: stress-cpu
  labels:
    app: stress-cpu
spec:
  replicas: 1
  selector:
    app: stress-cpu
  template:
    metadata:
      labels:
        app: stress-cpu
    spec:
      containers:
      - name: stress-cpu
        image: jess/stress
        args:
        - --cpu
        - "2"
