apiVersion: v1
kind: ReplicationController
metadata:
  name: cpu-load-generator
  labels:
    name: cpu-load-generator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cpu-load-generator
    spec:
      containers:
      - name: cpu-load-generator
        image: dongyiyang/cpu-load-generator:beta
        args:
        - -l
        - "0.1"
        resources:
          requests:
            cpu: 120m